# Generated by Django 3.2 on 2021-09-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210831_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='city',
            field=models.CharField(default='تهران', max_length=40, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='provice',
            field=models.CharField(default='تهران', max_length=30, verbose_name='استان'),
        ),
    ]
